### ISSUE TITLE
DMCA Takedown Notice on jsemu2

### ISSUE THREAD

**Issue by foopod** [ayvacs/gba.js.org#6]
Just an FYI that the jsemu2 repo has been taken down for...
```
"marketing or otherwise making available products and/or services that infringe 
on ESA Members’ copyrights and trademarks"

e.g.
• https://jsemu2.github.io/gba/launcher.html#advancewars
• https://jsemu2.github.io/gba/launcher.html#advancewars2
• https://jsemu2.github.io/gba/launcher.html#bomberman_max2blue
• https://jsemu2.github.io/gba/launcher.html#bomberman_tournament
```

[full report here](https://github.com/github/dmca/blob/master/2022/06/2022-06-21-esa.md)

And I noticed that your repo similarly uses licensed games to demo gba.js

It might be worth swapping these out with some open source games.

**Comment by ayvacs** [comment]
Thanks for the heads up! I'm working on a solution to this.

**Comment by kibabyte** [comment]
Anything new on this? It's amazing what you have created but i wonder if it's legal. Would be a shame if Nintendo or partners take it down.

**Comment by ayvacs** [comment]
@kibabyte I opened the site again a while ago (because honestly, fuck it) but it can be taken down at any time because it contains copyrighted files. If the site ever got threatened with a takedown, I could try moving the game files to a separate server but I think that could still go against DMCA for providing easy access to run those files (I'm not too familiar with US copyright laws and I haven't researched them at all)

If Nintendo ever takes notice of this, they would send GitHub a DMCA takedown request and I would be [given the opportunity to remove the copyrighted content](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#a-how-does-this-actually-work). If that happened I *guess* I could remove the copyrighted games and add in some open-source ones, but it really wouldn't be the same

Nintendo definitely has the legal grounds to send in a DMCA takedown request, they've taken down a few similar repo's - it's been almost half a year since jsemu2's repo got taken down and the author(s) haven't submitted a counter-request, or it was denied.

Wish Nintendo wasn't so restrictive on their IPs. it's a pain.
